
language: csharp
mono: none

dist: bionic
dotnet: 8.0

script:
- dotnet --version
- cd ./TestingExercise/TestingExercise/TestProject1
- dotnet restore
- dotnet build
- dotnet test ./TestProject1.csproj
