name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Instead of repeating the path for every step, 
    # we can set a global working directory for this job.
    defaults:
      run:
        working-directory: ./TestingExercise/TestingExercise

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore --configuration Release

      - name: Run NUnit Tests
        run: dotnet test --no-build --configuration Release --verbosity normal
